"use client";
import { useState } from "react";
import { Brush, CartesianGrid, Legend, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, PageHeader } from "@/components/ui";
import { relativeMarketSeries } from "@/lib/domain/relative-market";
import type { PricePoint } from "@/lib/domain/types";
const pairs=[{value:"VTI/BTC",label:"VTI / BTC"},{value:"BTC/IAU",label:"BTC / Altın (IAU vekili)"},{value:"VTI/IAU",label:"VTI / Altın (IAU vekili)"},{value:"QQQ/VTI",label:"Nasdaq (QQQ) / VTI"}];
const number=(n:unknown)=>Number(n).toLocaleString("tr-TR",{maximumSignificantDigits:6});
export function RelativeAnalysis(){
 const [pair,setPair]=useState("VTI/BTC"),[range,setRange]=useState("3y"),[series,setSeries]=useState<ReturnType<typeof relativeMarketSeries>>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[source,setSource]=useState(""),[levelText,setLevelText]=useState("");
 async function run(){setBusy(true);setError("");setSeries([]);try{const symbols=pair.split("/");const data=await Promise.all(symbols.map(async symbol=>{const response=await fetch(`/api/market/history?${new URLSearchParams({symbol,range,interval:"1d",allowPartial:"true"})}`,{signal:AbortSignal.timeout(60000)});if(!response.ok)throw new Error(`${symbol} tarihçesi alınamadı.`);return response.json() as Promise<{points:PricePoint[];source:string}>;}));const result=relativeMarketSeries(data[0].points,data[1].points);if(result.length<2)throw new Error("Ortak tarihli kapanış verisi yetersiz.");setSeries(result);setSource(data.map((d,i)=>`${symbols[i]}: ${d.source}`).join(" · "));}catch(e){setError(e instanceof Error?e.message:"Oran hesaplanamadı.");}finally{setBusy(false);}}
 const levels=levelText.split(";").map(s=>Number(s.trim().replace(",","."))).filter(n=>Number.isFinite(n)&&n>0).slice(0,5);
 return <div><PageHeader eyebrow="GÖRELİ GÜÇ" title="Varlıkları birbirine karşı izle" description="Oran yükselirse ilk varlık, düşerse ikinci varlık göreli olarak güçlenir."/>
 <Card><div className="settings-grid"><label className="field">Karşılaştırma<select className="select" disabled={busy} value={pair} onChange={e=>{setPair(e.target.value);setSeries([]);setLevelText("");}}>{pairs.map(p=><option value={p.value} key={p.value}>{p.label}</option>)}</select></label><label className="field">Dönem<select className="select" disabled={busy} value={range} onChange={e=>{setRange(e.target.value);setSeries([]);}}>{[1,3,5,10].map(y=><option value={`${y}y`} key={y}>{y} yıl</option>)}</select></label></div><button className="button primary section-gap" disabled={busy} onClick={()=>void run()}>{busy?"Fiyatlar alınıyor…":"Oran grafiğini göster"}</button>{error&&<p role="alert">{error}</p>}
 {series.length>0&&<><p className="section-gap">{pair}: <strong>{number(series.at(-1)!.ratio)}</strong> · RSI14: {series.at(-1)!.rsi===null?"—":number(series.at(-1)!.rsi)} · {series[0].date} – {series.at(-1)!.date}</p><label className="field">Kendi destek / direnç seviyelerin (noktalı virgülle ayır)<input className="input" value={levelText} onChange={e=>setLevelText(e.target.value)} placeholder="Örn. 0,003; 0,004"/></label>
 <div style={{height:380,width:"100%",minWidth:0}}><ResponsiveContainer width="100%" height="100%"><LineChart data={series}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" minTickGap={50}/><YAxis width={85} domain={["auto","auto"]} tickFormatter={number}/><Tooltip formatter={number}/><Legend/><Line isAnimationActive={false} name={pair} dataKey="ratio" stroke="#148774" dot={false} strokeWidth={2}/><Line isAnimationActive={false} name="EMA20" dataKey="ema20" stroke="#d59a27" dot={false}/><Line isAnimationActive={false} name="EMA50" dataKey="ema50" stroke="#7664c4" dot={false}/>{levels.map((level,i)=><ReferenceLine key={i} y={level} label={number(level)} stroke="#bd4c5d" strokeDasharray="4 4" ifOverflow="extendDomain"/>)}<Brush dataKey="date" height={24}/></LineChart></ResponsiveContainer></div>
 <details className="method-details"><summary>RSI grafiği ve hesaplama</summary><div style={{height:180,width:"100%",minWidth:0}}><ResponsiveContainer width="100%" height="100%"><LineChart data={series}><XAxis dataKey="date" minTickGap={70}/><YAxis domain={[0,100]} width={40}/><Tooltip formatter={number}/><ReferenceLine y={70} stroke="#c05656"/><ReferenceLine y={30} stroke="#29917e"/><Line isAnimationActive={false} dataKey="rsi" stroke="#7664c4" dot={false}/></LineChart></ResponsiveContainer></div><p>USD fiyatları aynı UTC tarihindeki kapanışlarla eşleştirilir. Borsa ve kripto kapanışları eşzamanlı değildir; ortak günü olmayan veri taşınmaz. EMA ve RSI, varlık fiyatına değil orana uygulanır. IAU altın vekilidir; BTC/XAU ons fiyatı değildir. Oran her iki varlık düşerken de yükselebilir; tek başına alım sinyali sayılmaz.</p><p>{series.length} ortak kapanış · {source}. Gösterilen tarihler mevcut kapsamdır; seçilen dönemin tamamı olmayabilir.</p></details></>}
 </Card></div>;
}
