import Link from "next/link";
import { Card, PageHeader } from "@/components/ui";
export default function ResearchPage() {
 return <div><PageHeader eyebrow="YÖNTEM" title="Düzenli alım, açık hesap" description="DCA: belirlediğin tutarı her ay aynı gün yatırmak."/>
 <Card><h2>Bu ayın planı</h2><p>Varsayılan yöntemde yeni para, hedef payın gerisindeki varlıklara göre dağıtılır. Böylece aylık alım yüzdeleri değişir; portföy kaydı yoksa hedef oranlarla başlar. İstersen profilden sabit katkı yüzdelerini seçebilirsin. Teknik sinyal beklenmez. BTC brüt %40 sınırı yeni alımlarda korunur; aşan pay sepetin diğer varlıklarına gider. Acil nakit ihtiyacı veya değerleme sorunu varsa bekleyen tutarın nedeni gösterilir.</p><p>Sepet ve takvim yatırım merkezinde değiştirilebilir. Mevcut varlıklar otomatik satılmaz, uygulama emir göndermez.</p><Link className="button primary" href="/">Yatırım merkezine dön</Link></Card>
 <Card className="section-gap"><h2>Geçmiş karşılaştırması</h2><p>BTC, VTI, Nasdaq-100 (QQQ), altın (IAU), her hisse %20 THYAO/HALKB/KCHOL/PETKM/ASELS ve kendi sabit sepetin; aynı aylık katkı ve yıllık ek ödemeyle ölçülür. Karşılaştırmadaki sepet her katkıyı sabit oranlarla alır; canlı plandaki hedef farkına veya BTC brüt sınırına göre yönlendirme uygulanmaz. BIST hisseleri tarihsel USD/TRY ile dolara çevrilir.</p><p>Altın satırı doğrudan XAU spot değil, altın fiyatını izleyen IAU vekilidir. Fiyat getirileri temettü ve vergiyi içermez. Eksik tarihçeli sonuçlar tam dönem sonuçlarıyla kıyaslanmaz.</p><p>Sepet taraması ilk %60 dönemde seçim, sonraki %40 dönemde ayrı kontrol yapar. Puan nominal XIRR eksi azami düşüşün yarısıdır; taranan sınırlı adaylar arasında yaklaşık bir kontrol, geleceğin optimumunu kanıtlayan sonuç değildir.</p><p>Yıllık reel getiri, katkı günlerini ve ABD enflasyonunu hesaba katar. %10 reel hedefi gelecek için garanti veya tahmin değildir.</p><Link className="button secondary" href="/backtest">DCA’ları karşılaştır</Link></Card>
 <details className="method-details section-gap"><summary>Kaynaklar ve ileri araçlar</summary><p>ABD fiyatları: Massive ve mevcut yedek sağlayıcılar. BTC: Binance ve mevcut yedekler. Kaynak ve kapsanan tarihler sonuçlarda gösterilir.</p><p><a href="https://www.invesco.com/qqq-etf/en/home.html">QQQ / Nasdaq-100</a> · <a href="https://www.ishares.com/us/products/239561/ishares-gold-trust-fund">IAU / altın</a> · <a href="https://www.bls.gov/cpi/">BLS / enflasyon</a></p><p>Önceki sanal swing kayıtlarına erişim korunur; bu araç DCA planının parçası değildir.</p><Link href="/swing">Sanal işlem defteri</Link></details>
 </div>;
}
