"use client";
import { screenDcaBaskets } from "@/lib/domain/dca-screen";
import { describeDcaBasket } from "@/lib/domain/dca-policy";
import { useMemo, useState } from "react";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { runDcaBacktest, DCA_SYMBOLS, type DcaHistory, type DcaResult, type DcaSymbol } from "@/lib/domain/dca-backtest";
import { investmentRepository, downloadInvestmentFile } from "@/lib/storage/investment-repository";
import { settingsRepository } from "@/lib/storage/settings-repository";
import type { PricePoint } from "@/lib/domain/types";
import { Card, PageHeader } from "@/components/ui";
const money=(n:number)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const pct=(n:number|null)=>n===null?"—":`%${(n*100).toFixed(1)}`;
const colors=["#d68b20","#3678dd","#8763ce","#ae822d","#148774","#e15976"];
export function OpportunityBacktestPanel(){
 const [years,setYears]=useState<3|5|10>(5),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[result,setResult]=useState<DcaResult|null>(null);
 async function run(){setBusy(true);setError(null);setResult(null);setSaved("");try{
  const [policy,settings]=await Promise.all([investmentRepository.getPolicy(),settingsRepository.get()]);
  const end=new Date(),start=new Date(end);start.setUTCFullYear(start.getUTCFullYear()-years);start.setUTCDate(start.getUTCDate()-8);
  const getHistory=async(symbol:string):Promise<DcaHistory>=>{try{const query=new URLSearchParams({symbol,range:`${years}y`,interval:"1d",allowPartial:"true",from:start.toISOString(),to:end.toISOString()});const response=await fetch(`/api/market/history?${query}`,{signal:AbortSignal.timeout(180000)});if(!response.ok)return {points:[],source:"Veri alınamadı"};const data=await response.json();return {points:data.points,source:data.source};}catch{return {points:[],source:"Bağlantı hatası"};}};
  const symbols=DCA_SYMBOLS.filter(s=>s!=="BIST100"||policy.dcaWeights.turkishEquity>0);
  const [histories,cpi,fx]=await Promise.all([Promise.all(symbols.map(async s=>[s,await getHistory(s)] as const)),fetch("/api/market/macro-history?series=CPIAUCSL",{signal:AbortSignal.timeout(30000)}).then(async r=>r.ok?await r.json() as {points:PricePoint[]}:{points:[]}).catch(()=>({points:[]})),getHistory("USDTRY")]);
  setResult(runDcaBacktest({histories:Object.fromEntries(histories) as Partial<Record<DcaSymbol,DcaHistory>>,fxHistory:fx.points,cpiHistory:cpi.points,years,monthlyUsd:settings.monthlyBudgetUsd,policy,endDate:end.toISOString()}));
 }catch(cause){setError(cause instanceof Error?cause.message:"Karşılaştırma hesaplanamadı.");}finally{setBusy(false);}}
 const scan=useMemo(()=>result?screenDcaBaskets(result):null,[result]);
 const [saved,setSaved]=useState("");
 async function applyCandidate(){if(!scan?.available||!scan.supported)return;try{const policy=await investmentRepository.getPolicy();await investmentRepository.savePolicy({...policy,dcaWeights:scan.weights});setSaved("Hedef sepet kaydedildi. Yatırım merkezine döndüğünde yeni katkı bu hedeflere göre hesaplanır.");}catch{setSaved("Sepet kaydedilemedi.");}}
 const chart=result?.rows[0].curve.filter((p,i,all)=>i===0||i===all.length-1||p.date.slice(0,7)!==all[i-1].date.slice(0,7)).map(p=>{const index=result.rows[0].curve.indexOf(p);return {date:p.date.slice(0,10),Katkı:p.contributed,...Object.fromEntries(result.rows.map(r=>[r.name,r.curve[index]?.value]))};})??[];
 return <div><PageHeader eyebrow="DÜZENLİ ALIM" title="DCA karşılaştırması" description="Aynı gün, aynı katkı. BTC, ABD hisseleri, Nasdaq, altın ve kendi sepetin."/>
  <Card><div className="allocation-actions"><label className="field">Geçmiş dönem<select className="select" disabled={busy} value={years} onChange={e=>{setYears(Number(e.target.value) as 3|5|10);setResult(null);}}>{[3,5,10].map(n=><option value={n} key={n}>{n} yıl</option>)}</select></label><button className="button primary" disabled={busy} onClick={()=>void run()}>{busy?"Geçmiş fiyatlar alınıyor…":"DCA’ları karşılaştır"}</button></div><p className="small-copy muted">Aylık tutar ve sepet, yatırım merkezindeki profilinden alınır. Varsayımsal rezerv faizi yok.</p>{error&&<p role="alert">{error}</p>}</Card>
  {result&&<><p className="section-gap small-copy">{result.start.slice(0,10)} – {result.end.slice(0,10)} · {result.contributionRule}</p>
  <Card><div className="table-wrap"><table className="data-table"><thead><tr><th>Yöntem / her katkının dağılımı</th><th>Yatırılan</th><th>Son birikim</th><th>Net kazanç</th><th>Yıllık reel getiri</th></tr></thead><tbody>{result.rows.map(row=><tr key={row.name}><td><strong>{row.name}</strong><br/><small>{row.basket}</small>{!row.complete&&<p className="negative small-copy">Eksik kapsam · karşılaştırmaya uygun değil</p>}</td><td>{money(row.contributedUsd)}</td><td>{money(row.endingUsd)}</td><td>{money(row.gainUsd)}</td><td>{row.complete?pct(row.realXirr):"—"}</td></tr>)}</tbody></table></div><p className="small-copy muted">Yıllık reel getiri: katkı tarihlerine göre hesaplanan ve ABD enflasyonundan arındırılan XIRR. Geçmiş sonuç, gelecek getiri hedefi değildir.</p></Card>
  <Card className="section-gap"><h2>Birikimin seyri</h2><div style={{height:300,width:"100%",minWidth:0}}><ResponsiveContainer width="100%" height="100%"><LineChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tickFormatter={v=>String(v).slice(0,7)} minTickGap={45}/><YAxis width={65} tickFormatter={v=>`${Math.round(Number(v)/1000)} bin`}/><Tooltip formatter={v=>money(Number(v))}/><Legend/><Line dataKey="Katkı" stroke="#8995a5" strokeDasharray="5 5" dot={false}/>{result.rows.filter(r=>r.complete).map(r=><Line key={r.name} dataKey={r.name} stroke={colors[result.rows.indexOf(r)]} dot={false}/>)}</LineChart></ResponsiveContainer></div><p className="small-copy">Kesikli çizgi toplam katkı. Yalnız tam kapsamlı yöntemlerin değer eğrileri gösterilir.</p></Card>
  <details className="method-details section-gap"><summary>Hedef sepet taraması · ayrı doğrulama dönemi</summary>{scan?.available?<><p>{scan.tested} aday arasından seçim: <strong>{describeDcaBasket(scan.weights)}</strong></p><p>Seçim sonu: {scan.selectedUntil.slice(0,10)}. Bundan sonraki dönem: aday yıllık nominal {pct(scan.validation.annual)}, azami düşüş {pct(scan.validation.drawdown)}; mevcut sepet yıllık nominal {pct(scan.baseline.annual)}, düşüş {pct(scan.baseline.drawdown)}.</p><p>{scan.supported?"Aday, ayrı doğrulama döneminde tanımlı puan ve düşüş koşullarını geçti. İstersen hedef olarak kullanabilirsin.":"Aday ayrı doğrulama koşullarını geçmedi. Mevcut hedefi değiştirmek için bu taramada yeterli dayanak yok."}</p><p className="small-copy muted">{scan.note}</p>{scan.supported&&<button className="button secondary" onClick={()=>void applyCandidate()}>Bu hedefleri uygula</button>}<p role="status">{saved}</p></>:<p>{scan?.reason}</p>}</details>
  <details className="method-details section-gap"><summary>Maliyet, düşüş ve veri kapsamı</summary><div className="table-wrap"><table className="data-table"><thead><tr><th>Yöntem</th><th>Nominal yıllık</th><th>Azami düşüş</th><th>Nakit</th><th>Maliyet</th><th>Alım</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.name}><td>{r.name}</td><td>{pct(r.xirr)}</td><td>{pct(r.maxDrawdown)}</td><td>{money(r.cashUsd)}</td><td>{money(r.costsUsd)}</td><td>{r.orders}</td></tr>)}</tbody></table></div><p>Alım maliyeti: %{result.feeBps/100}. Yıllık ek ödeme geçmişte her yıl aynı ayda varsayılır; gelecekteki ilk ödeme yılı geçmişi kesmez.</p>{result.warnings.map(w=><p key={w}>{w}</p>)}{result.coverage.filter(c=>c.symbol!=="BIST100"||c.first).map(c=><p key={c.symbol}>{c.symbol}: {c.first?.slice(0,10)??"Veri yok"} – {c.last?.slice(0,10)??"Veri yok"} · {c.source}</p>)}<p><a href="https://www.invesco.com/qqq-etf/en/home.html" target="_blank" rel="noreferrer">QQQ: Nasdaq-100</a> · <a href="https://www.ishares.com/us/products/239561/ishares-gold-trust-fund" target="_blank" rel="noreferrer">IAU: altın fiyatı vekili</a></p><button className="button secondary" onClick={()=>downloadInvestmentFile(`dca-${years}-yil.json`,result)}>Sonuçları indir</button></details></>}
 </div>;
}
